services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    restart: always
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    networks:
      - fastapi_network

  nginx_server:
    image: nginx:1.29.2-alpine
    container_name: nginx_server
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/static:/app/src/static
    depends_on:
      - fastapi_app
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
